---
# Database name used for syncing 
db_sync: "KodiFileSync"

# tuples specifying (kodi version, database name) for two or more Kodi databases
# NOTE: One line per Kodi version.
kodi_dbs:
  - !!python/tuple [18, "MyVideos116"]
  - !!python/tuple [19, "MyVideos119"]
  - !!python/tuple [20, "MyVideos121"]

# (Optional) CAUTION: only change if you know are familiar with the syncing logic 
steps:
  create_sync_database: true
  create_triggers: true
  push_inserts: true
  create_views: true
  create_events: true
